<?php
define('CATEGORIES', [
    'action' => 'Hành động',
    'adventure' => 'Phiêu lưu',
    'comedy' => 'Hài hước',
    'drama' => 'Drama',
    'fantasy' => 'Fantasy',
    'romance' => 'Tình cảm',
    'horror' => 'Kinh dị',
    'mystery' => 'Bí ẩn',
    'psychological' => 'Tâm lý',
    'sci-fi' => 'Khoa học viễn tưởng',
    'slice-of-life' => 'Đời thường',
    'sports' => 'Thể thao',
    'supernatural' => 'Siêu nhiên',
    'martial-arts' => 'Võ thuật',
    'school-life' => 'Học đường',
    'shounen' => 'Shounen',
    'shoujo' => 'Shoujo',
    'seinen' => 'Seinen',
    'josei' => 'Josei',
    'mecha' => 'Mecha',
    'magic' => 'Phép thuật',
    'military' => 'Quân sự',
    'historical' => 'Lịch sử',
    'music' => 'Âm nhạc',
    'game' => 'Game',
    'isekai' => 'Dị giới',
    'demons' => 'Quỷ vật',
    'vampire' => 'Ma cà rồng',
    'harem' => 'Harem',
    'ecchi' => 'Ecchi'
]);
